In [1]:
import numpy as np

In [2]:
test = np.arange(20)
test = test.reshape(4,5)
print(test)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
(9 + 1) % 5 + 9 // 5 * 5

5